options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
           'gcr.io/terraform-on-gcp-428202/terraform/solo', 
           '.']

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 
           'gcr.io/terraform-on-gcp-428202/terraform/solo']
