options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/" + '${TF_VAR_PROJECT_ID}' + "/serviceAccounts/" + '${TF_VAR_SA_EMAIL}'

steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-build'
    args:
      - 'build'
      - '-t'
      - 'us.gcr.io/${TF_VAR_PROJECT_ID}/terraform/solo:latest'
      - '.'

  # Docker Push
  - name: 'gcr.io/cloud-builders/docker'
    id: 'docker-push'
    args:
      - 'push'
      - 'us.gcr.io/${TF_VAR_PROJECT_ID}/terraform/solo:latest'

  # Prepare Deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'prepare-deploy'
    args:
      - 'prepare'
      - '--filename=k8s/'
      - '--image=us.gcr.io/${TF_VAR_PROJECT_ID}/terraform/solo:latest'

  # Apply Deploy
  - name: 'gcr.io/cloud-builders/gke-deploy'
    id: 'apply-deploy'
    args:
      - 'apply'
      - '--filename=output/expanded'
      - '--cluster=primary'
      - '--location=${TF_VAR_COMPUTE_REGION}'
      - '--namespace=default'
