apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    type: backend
    app: nodeapp
spec: 
  replicas: 1
  selector:
    matchLabels:
      type: backend
      app: nodeapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      name: nodeapppod
      labels:
        type: backend
        app: nodeapp
    spec:
      containers:
        - name: nodeappcontainer
          image: us.gcr.io/terraform-on-gcp-428202/terraform/solo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80